### ISSUE TITLE
Error with latest commit.

### ISSUE THREAD

**Issue by davinchia** [mikaoj/BSGridCollectionViewLayout#1]
The latest commit has seemed to introduce an off by one error in GridCollectionViewLayout.swift.

When I build my project, xcode throws **"fatal error: Can't form Range with end < start**. 

This seems to be originating from line 150 in the file,
let indexPaths = (startIndex...endIndex).map { indexPathFromFlatIndex($0) } 

My guess is because endIndex is assigned in line 148,
let endIndex = (endRow \* itemsPerRow + itemsPerRow > items) ? items-1 : endRow \* itemsPerRow,
it is mistakenly set to -1.

I fixed this in my project by replacing this portion of the code with the previously used for loop and thought you might want to look into this.

**Comment by sherifnada** [comment]
^ +1 came here to say this -- currently fixed it by copy-pasting the for loop you had in place earlier.

**Comment by mikaoj** [comment]
Thanks, I'll look into it!

**Comment by mikaoj** [comment]
Update to 1.1.1. Thanks again for reporting it!
