### ISSUE TITLE
Support for Bitcode

### ISSUE THREAD

**Issue by AlexV525** [mikaoj/BSGridCollectionViewLayout#11]
**Describe the bug**
Build with `Enable Bitcode` failed. Related to https://github.com/Sh1d0w/multi_image_picker/issues/368

**To Reproduce**
1. Using `multi_image_picker` for flutter project.
2. Build release with bitcode enabled.

**Expected behavior**
The library support bitcode.

**Error Log**
```
ld: '/Users/alex/SomeFlutterProject/build/ios/Release-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.framework/BSGridCollectionViewLayout' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/alex/SomeFlutterProject/build/ios/Release-iphoneos/BSGridCollectionViewLayout/BSGridCollectionViewLayout.framework/BSGridCollectionViewLayout' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Extra Info**

Idk why we have to talk like this, developers should done this to each other? **BAN** someone from new issue? It's just a technical question, you can just say whether it will support or not, instead of closing it without any info provided, that's not open source sharing works like. The kind of attitude will make developers **NEVER use the package again**.

**Comment by mikaoj** [comment]
> Idk why we have to talk like this, developers should done this to each other? BAN someone from new issue? It's just a technical question, you can just say whether it will support or not, instead of closing it without any info provided, that's not open source sharing works like. The kind of attitude will make developers NEVER use the package again.

Try the latest version (3.0.0), as far as I can see bitcode should be enabled in it.

And as for how open source should work I prefer actual contribution over 'fix X for me'.
I've been maintaining it for 6 years but had very little contribution from other developers.

So if this or something else isn't working open a pull request where the issue can be reproduced, tested, fixed, documented, whatever and we can take it from there.
I'm not doing it to piss people off, I'm trying to encourage more active contribution.

I'll paste in the contribution section from the README:

## Contribution

This project does not come with GitHub Issues-based support, and users are instead encouraged to become active participants in its continued development — by fixing any bugs that they encounter, or by improving the documentation wherever it’s found to be lacking.

If you wish to make a change, [open a Pull Request](https://github.com/mikaoj/BSImagePicker/pull/new) — even if it just contains a draft of the changes you’re planning, or a test that reproduces an issue — and we can discuss it further from there.

**Comment by mikaoj** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/4034956/72673874-29c8e000-3a70-11ea-83ee-e2e862604ed1.png">

**Comment by AlexV525** [comment]
Thanks for your contribution with those packages! What I can do is provide a demo as specific as possible, cause using package with another package which required different kind of tech stack, makes me hard to understand why this happened or what I can do to 'fix it'. In flutter side if I found some issues that I can handle with, I'll PR to make it worked, but out of my knowledge I can only bring issues to ask the owner if this can be done.

Again, thanks for your reply and dedication 👍. I'll mention him for an update and further tests.
