### ISSUE TITLE
Crash due to invalid range parameters in indexPathsInRect

### ISSUE THREAD

**Issue by jonshoe** [mikaoj/BSGridCollectionViewLayout#4]
Hello!  Thanks for creating this pod and the BSImagePicker pod!

Our project recently encountered a crashing issue in the following scenario:
- Using BSImagePicker, scroll to the end of a very large camera roll
- Switch to a much smaller album from the album list
- Crash with `fatal error: Can't form Range with end < start` in `indexPathsInRect:`

Values at crash:

```
rect    CGRect  (origin = (x = 0, y = 62480), size = (width = 320, height = 1136))  
self    BSGridCollectionViewLayout.GridCollectionViewLayout 0x000000012f8af4e0
rowHeight   CGFloat 107.33333333333333  
startRow    Int 582
endRow  Int 4
startIndex  Int 1746
endIndex    Int 13
indexPaths  [NSIndexPath]   
rows 5
```

Our project is resolving this for now in a private fork by adding this guard function for invalid values, right before attempting to create the range of indices:
`guard startIndex <= endIndex else { return [] }`

**Comment by mikaoj** [comment]
Thanks! Feel free to set up a PR again, with the fix, if you want :)
